### ISSUE TITLE
Issue building icons

### ISSUE THREAD

**Issue by deveti** [Ympact/flux-icons#1]
Hi!

I tried to install the package and build the tabler icons as per instructions and I got the following error:

```
artisan flux-icons:build tabler --all

 Are you sure you want to build all icons for vendor: tabler? (yes/no) [no]:
 > yes

Installing package for vendor: tabler
Building icons for vendor: tabler

ErrorException
Undefined variable $outlineIcons at vendor/ympact/flux-icons/src/Services/IconBuilder.php:83
```

I am using a fresh Laravel install with Flux on Sail.

**Comment by mauritskorse** [comment]
Thanks for reporting. Will be fixed in next update.
I hadn't tested --all anynore since it overloaded my project with thousands of files ;) I guess I should write a test for it.

**Comment by mauritskorse** [comment]
The issue should be fixed now. 

I have added some notes in the readme on the --all option. It might crash your `npm run dev` due to many files that are being generated.

**Comment by mauritskorse** [comment]
The issue should be fixed now. 

I have added some notes in the readme on the --all option. It might crash your `npm run dev` due to many files that are being generated.
